### ISSUE TITLE
Select this template link incorrect

### ISSUE THREAD

**Issue by hhenline** [web-q/landing-page-gallery#85]
@albertkoncz @halvves - When I click on select this template button, it directs to the main ZenDesk forms page, instead of the Landing Page ticket. This may have happened when we removed the FW1 section. Can you all take a look? Thanks!

**Comment by halvves** [comment]
Email from albert documenting the URL change:

>Hey Cody

>The Zendesk support form URLs have been changed.

>Could you please change the link of the “Select This Template” button

>from https://webq.zendesk.com/hc/en-us/requests/new?form=/hut/campaign-landing-page&formparams=LPGID 

>to https://webq.zendesk.com/hc/en-us/requests/new?form=/campaign-landing-page/new&formparams=LPGID  


>ex.:

>from https://webq.zendesk.com/hc/en-us/requests/new?form=/hut/campaign-landing-page&formparams=7e41aa

>to https://webq.zendesk.com/hc/en-us/requests/new?form=/campaign-landing-page/new&formparams=7e41aa 


>Thanks,
>Albert
